// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Extract(arg1:main.ExtractRequest):Promise<Record<string, any>>;

export function GenerateCode(arg1:main.CodeGenRequest):Promise<Record<string, any>>;

export function Reset():Promise<main.ResetResponse>;
