// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Extract(arg1) {
  return window['go']['main']['App']['Extract'](arg1);
}

export function Reset() {
  return window['go']['main']['App']['Reset']();
}
